// Generated by BAML tooling.v1. Do not edit.
// baml-fingerprint: 5a918d96163033a5095c5c3a5889a238ceef69e7f84a443b24319962105a8e40

export interface Person {
  name: string;
}

export interface Person$stream {
  name: string | null;
}

export interface BamlClient {
}
export declare const b: BamlClient;
